version: '3.8'

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/app.py
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=db_name
volumes:
  postgres_data:
