"""empty message

Revision ID: cb85652478e3
Revises:
Create Date: 2020-10-24 13:02:41.358973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb85652478e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('min_salary', sa.String(length=500), nullable=False),
    sa.Column('max_salary', sa.String(length=500), nullable=False),
    sa.Column('avg_salary', sa.String(length=500), nullable=False),
    sa.Column('education', sa.String(length=500), nullable=False),
    sa.Column('short_description', sa.String(length=1000), nullable=False),
    sa.Column('long_description', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
